spring:
  jpa:
    show-sql: true
    properties:
      eclipselink:
        show-sql: true
  main:
    allow-bean-definition-overriding: false

logging:
  level:
    com.summa: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: INFO
