spring:
  jpa:
    show-sql: false

logging:
  file:
    path: ${SUMMA_LOG_DIR:/data/logs}
    name: ${SUMMA_LOG_DIR:/data/logs}/summa.log
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} [%thread] %-5level %logger{36} - %msg%n"

